POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRpbmRvbmcxMjMiLCJpZCI6IjY2YzUwNTk3MTJhYTU5NjJlNjRiN2E2YiIsImlhdCI6MTcyNDM1MjE0NX0.H3BCl8PcPuGiMiUOR2yffwsYoOIMyToOIQrloJLVl5Y

{
    "title": "Another",
    "author": "One",
    "url": "http://www.something.html",
    "userId": "66c5059712aa5962e64b7a6b"
}